### ISSUE TITLE
Inplace operation Error when backwarding

### ISSUE THREAD

**Issue by Ainevsia** [yujianke100/GFDN#4]
Dear author,

I have been actively exploring the functionalities of your project. Before I explain the issue, I would like to apologize for any inconvenience caused. I must admit that I am still in the process of fully grasping all aspects of the codebase, and as a result, I have encountered a problem that I am unable to resolve. I have included the relevant code snippet below to help illustrate the issue:

```bash
start ComShrDecom
n1: 532345 n2: 239840
D1: 696812 D2: 2
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
start query
finished!
max b:11
[+] not os.path.exists /model/model_100.pkl
AE(
  (enc_in): Linear(in_features=87, out_features=128, bias=True)
  (hidden_enc): ModuleList(
    (0): Linear(in_features=128, out_features=128, bias=True)
  )
  (z_layer): Linear(in_features=128, out_features=64, bias=True)
  (dec_in): Linear(in_features=64, out_features=128, bias=True)
  (hidden_dec): ModuleList(
    (0): Linear(in_features=128, out_features=128, bias=True)
  )
  (x_bar_layer): Linear(in_features=128, out_features=87, bias=True)
)
GNN(
  (core_u): CORE()
  (core_i): CORE()
  (ae): AE(
    (enc_in): Linear(in_features=87, out_features=128, bias=True)
    (hidden_enc): ModuleList(
      (0): Linear(in_features=128, out_features=128, bias=True)
    )
    (z_layer): Linear(in_features=128, out_features=64, bias=True)
    (dec_in): Linear(in_features=64, out_features=128, bias=True)
    (hidden_dec): ModuleList(
      (0): Linear(in_features=128, out_features=128, bias=True)
    )
    (x_bar_layer): Linear(in_features=128, out_features=87, bias=True)
  )
  (tl): TL(
    (to_label1): Linear(in_features=8, out_features=4, bias=True)
    (to_label2): Linear(in_features=4, out_features=2, bias=True)
  )
  (tel): TEL(
    (to_edge_label1): Linear(in_features=179, out_features=64, bias=True)
    (to_edge_label2): Linear(in_features=64, out_features=2, bias=True)
  )
  (i_emb): Linear(in_features=72, out_features=76, bias=True)
  (gnn_in): SAGE_NET(
    (gcn): SAGEConv(87, 128, aggr=mean)
  )
  (hidden_gnn): ModuleList(
    (0): SAGE_NET(
      (gcn): SAGEConv(128, 128, aggr=mean)
    )
  )
  (gnn_nz): SAGE_NET(
    (gcn): SAGEConv(128, 64, aggr=mean)
  )
  (gnn_cluster): SAGE_NET(
    (gcn): SAGEConv(64, 8, aggr=mean)
  )
)
Namespace(lr=0.001, n_clusters=8, n_z=64, epoch=100, hidden_dim=128, pre_ae_epoch=150, seed=10, hidden=1, ll=0.1, el=0.6, al=0.2, kl=0.1, th=0.45, gnn='sage', cuda=True)

  0%|          | 0/86 [00:00<?, ?it/s]/mnt/hdddata/xzp/GFDN/main.py:237: UserWarning: Anomaly Detection has been enabled. This mode will increase the runtime and should only be enabled for debugging.
  with torch.autograd.detect_anomaly():
/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/autograd/__init__.py:251: UserWarning: Error detected in ReluBackward0. Traceback of forward call that caused the error:
  File "/mnt/hdddata/xzp/GFDN/main.py", line 367, in <module>
    train_exp(dataset,focal_loss)
  File "/mnt/hdddata/xzp/GFDN/main.py", line 299, in train_exp
    loss, f1, auc = train(adjs, n_id,model,optimizer,dataset,focal_loss)
  File "/mnt/hdddata/xzp/GFDN/main.py", line 213, in train
    x_, x_bar, q = model(x, edge_u_x, edge_u_id, adjs.edge_index)    # inplace !!!
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/hdddata/xzp/GFDN/main.py", line 140, in forward
    x = self.gnn_nz(x, edge_index)
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/hdddata/xzp/GFDN/GNN.py", line 18, in forward
    x = F.relu(x)
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/nn/functional.py", line 1471, in relu
    result = torch.relu(input)
 (Triggered internally at /opt/conda/conda-bld/pytorch_1702400366987/work/torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

  0%|          | 0/86 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/hdddata/xzp/GFDN/main.py", line 367, in <module>
    train_exp(dataset,focal_loss)
  File "/mnt/hdddata/xzp/GFDN/main.py", line 299, in train_exp
    loss, f1, auc = train(adjs, n_id,model,optimizer,dataset,focal_loss)
  File "/mnt/hdddata/xzp/GFDN/main.py", line 238, in train
    loss.backward() ### BOOM !
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/mnt/hdddata/xzp/anaconda3/envs/gfdn/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [16621, 64]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

```

The problem I am facing is that backwarding fails due to some kind of inplace operation related to some torch.cuda.FloatTensor [16621, 64]. 

I have a doubt regarding the line x, x_bar, q = model(x, edge_u_x, edge_u_id, adjs.edge_index) and whether it performs an inplace operation. I attempted to rename it, but it did not resolve the issue.

In my environment, I am using a 3080, which may not be powerful enough to handle a n_clusters value of 32. As a workaround, I have modified the n_clusters to a smaller value, which I believe does not contribute to the aforementioned problem.

Since my GPU does not support python3.8 and your provide cuda version, I used python3.10 and latest pytorch, and I am not sure if this caused the problem.

Apart from this change, I have made no other modifications.

My current main.py is linked [here](https://github.com/Ainevsia/GFDN/blob/main/main.py) if it can be any help.

Given your deep expertise in this field and your familiarity with the project, I am reaching out to kindly request your guidance. Could you please help me understand why I am encountering this issue and provide me with some instructions or suggestions to overcome it? I would greatly appreciate any insights or pointers you can offer.

Thank you very much for your time and consideration. I truly admire your work and look forward to your guidance.

**Comment by yujianke100** [comment]
If the old version cannot be used, please replace all the RELUs in GNN.py:

```
def custom_relu(x):
    return torch.where(x > 0, x, torch.tensor(0.0))
```
